/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quincrm;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;

/**
 *
 * @author cuong
 */
public class LoginGUI extends javax.swing.JFrame {

    //class
    CurrentUser currentUser = new CurrentUser();

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:derby:QuinDatabase;create=truePU").createEntityManager();
        userDatQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM UserDat u");
        userDatList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(userDatQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        usernameTXT = new javax.swing.JTextField();
        passwordTXT = new javax.swing.JPasswordField();
        usernameLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        loginBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jUserTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        loginLBL = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 370));

        usernameTXT.setBackground(new java.awt.Color(51, 51, 51));
        usernameTXT.setForeground(new java.awt.Color(204, 204, 204));
        usernameTXT.setBorder(null);
        usernameTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTXTFocusGained(evt);
            }
        });
        usernameTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameTXTKeyPressed(evt);
            }
        });

        passwordTXT.setBackground(new java.awt.Color(51, 51, 51));
        passwordTXT.setForeground(new java.awt.Color(204, 204, 204));
        passwordTXT.setBorder(null);
        passwordTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTXTFocusGained(evt);
            }
        });
        passwordTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTXTKeyPressed(evt);
            }
        });

        usernameLBL.setForeground(new java.awt.Color(102, 102, 102));
        usernameLBL.setText("Username");

        passwordLBL.setForeground(new java.awt.Color(102, 102, 102));
        passwordLBL.setText("Password");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        loginBTN.setBackground(new java.awt.Color(51, 51, 51));
        loginBTN.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN.setText("Log In");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(51, 51, 51));
        backBTN.setForeground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        jUserTable.setName(""); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, userDatList, jUserTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userID}"));
        columnBinding.setColumnName("User ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userfname}"));
        columnBinding.setColumnName("Userfname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userlname}"));
        columnBinding.setColumnName("Userlname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usernick}"));
        columnBinding.setColumnName("Usernick");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userpass}"));
        columnBinding.setColumnName("Userpass");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jUserTable);
        if (jUserTable.getColumnModel().getColumnCount() > 0) {
            jUserTable.getColumnModel().getColumn(0).setMinWidth(0);
            jUserTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            jUserTable.getColumnModel().getColumn(1).setMinWidth(0);
            jUserTable.getColumnModel().getColumn(1).setPreferredWidth(0);
            jUserTable.getColumnModel().getColumn(2).setMinWidth(0);
            jUserTable.getColumnModel().getColumn(2).setPreferredWidth(0);
            jUserTable.getColumnModel().getColumn(3).setMinWidth(0);
            jUserTable.getColumnModel().getColumn(3).setPreferredWidth(0);
            jUserTable.getColumnModel().getColumn(4).setMinWidth(0);
            jUserTable.getColumnModel().getColumn(4).setPreferredWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordLBL)
                            .addComponent(usernameLBL)
                            .addComponent(jSeparator1)
                            .addComponent(passwordTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(loginBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameTXT))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(usernameLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBTN)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 367));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        loginLBL.setFont(new java.awt.Font("Century Gothic", 0, 56)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(204, 204, 204));
        loginLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLBL.setText("LOG IN");
        loginLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(loginLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(loginLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 367));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTXTFocusGained
        usernameLBL.setForeground(new Color(204, 204, 204));
        passwordLBL.setForeground(new Color(102, 102, 102));

        //set Caret Color
        usernameTXT.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_usernameTXTFocusGained

    private void passwordTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTXTFocusGained
        passwordLBL.setForeground(new Color(204, 204, 204));
        usernameLBL.setForeground(new Color(102, 102, 102));

        //set Caret Color
        passwordTXT.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_passwordTXTFocusGained

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        //Get text
        String username = usernameTXT.getText().toLowerCase();
        String password = passwordTXT.getText();

        //Run query
        userDatList.clear();
        userDatQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM UserDat u WHERE u.usernick = '" + username + "' AND u.userpass = '" + password + "'");
        userDatList.addAll(userDatQuery.getResultList());
        System.out.println(userDatList);
        //repaint jTable
        jUserTable.repaint();

        //Validation to log in
        if (userDatList.isEmpty()) {
            System.out.println("nope");
            UserMessage6GUI show6 = new UserMessage6GUI();
            show6.setLocationRelativeTo(null);
            show6.setVisible(true);
        } else {
            System.out.println("Welcome");
            //setting user's first name
            currentUser.setFname(returnFname().toString());
            System.out.println(returnFname().toString());
            //setting user's last name
            currentUser.setLname(returnLname().toString());
            System.out.println(returnLname().toString());
            //setting user's username
            currentUser.setUsername(username);
            System.out.println(username);
            //setting user's pass
            currentUser.setUserpass(password);
            System.out.println(password);
            //setting user directory path
            String loggeduser = System.getenv("USERPROFILE");
            currentUser.setUserPC(loggeduser);
            
            //Has User Folder Been Deleted?
            File userDirectory = new File(loggeduser + "\\Documents\\QuinCRM\\" + usernameTXT.getText());
            File logsDirectory = new File(loggeduser + "\\Documents\\QuinCRM\\" + usernameTXT.getText() + "\\Logs");
            File graphsDirectory = new File(loggeduser + "\\Documents\\QuinCRM\\" + usernameTXT.getText() + "\\Graphs");

            if (!userDirectory.exists()) {
                userDirectory.mkdirs();
                logsDirectory.mkdirs();
                graphsDirectory.mkdirs();
                System.out.println("User Directory has been created");
            } else {
                System.out.println("UserDirectory already exists");
            }

            MainGUI show = new MainGUI();
            show.setVisible(true);
            show.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_loginBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        InitialGUI show = new InitialGUI();
        show.setVisible(true);
        show.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backBTNActionPerformed

    private void passwordTXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTXTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginBTN.doClick();
        }
    }//GEN-LAST:event_passwordTXTKeyPressed

    private void usernameTXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTXTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginBTN.doClick();
        }
    }//GEN-LAST:event_usernameTXTKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jUserTable;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTXT;
    private java.util.List<quincrm.UserDat> userDatList;
    private javax.persistence.Query userDatQuery;
    private javax.swing.JLabel usernameLBL;
    private javax.swing.JTextField usernameTXT;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public Object returnFname() {
        Object fname = jUserTable.getValueAt(0, 1);
        //return value for calling method
        return fname;
    }

    public Object returnLname() {
        Object lname = jUserTable.getValueAt(0, 2);
        //return value for calling method
        return lname;
    }
}
